[build]
  publish = "build"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_PUBLIC_SITE_URL = "https://convohunter-clone.same-app.com"

[images]
  remote_images = [
    "https://ext.same-assets.com/259716110/**"
  ]
